feat: Implement MedRecordValue
limebit/medmodels pull request #16
Opened 2024-02-18 16:21 UTC by JabobKrauskopf

2024-02-18 16:22 UTC, JabobKrauskopf commented on crates/medmodels-core/src/medrecord/values.rs
> +macro_rules! implement_from {
Rust is sooooooo amazing for enabling stuff like this

2024-02-19 10:01 UTC, JabobKrauskopf commented on rustmodels/src/medrecord/conversion.rs
> +pub trait DeepFrom<T> {
Also checkout the magic implemented with `DeepFrom`

2024-02-19 11:54 UTC, FloLimebit requested changes
maybe we should add a little description in the readme that the installation of rust is needed if someone wants to install medmodels from source. Quick guide on how to install rust (basically two lines i guess)

2024-02-19 12:02 UTC, JabobKrauskopf commented
> maybe we should add a little description in the readme that the installation of rust is needed if someone wants to install medmodels from source. Quick guide on how to install rust (basically two lines i guess)

@FloLimebit I agree but I would suggest that this should be addressed in a different issue/pr (https://github.com/limebit/medmodels/issues/22)

2024-02-19 12:10 UTC, FloLimebit approved these changes

2024-02-19 12:11 UTC, merged