refactor: implement new querying interface
limebit/medmodels pull request #191
Opened 2024-09-03 10:25 UTC by JabobKrauskopf

2024-09-03 11:22 UTC, JabobKrauskopf commented
Usage examples:

```python
def query(node: NodeOperand):
    edges_to_treatment = node.outgoing_edges()
    edges_to_treatment.target_node().in_group("treatment")

    edges_to_outcome = node.outgoing_edges()
    edges_to_outcome.target_node().in_group("outcome")

    max_time_edge = edges_to_treatment.attribute("time").max()

    max_time_edge.less_than(edges_to_outcome.attribute("time"))


medrecord.select_nodes(query)
```

2024-09-03 15:03 UTC, LauraBoenchenLB requested changes

2024-09-03 15:07 UTC, JabobKrauskopf commented on medmodels/medrecord/querying.pyi
> +    def either_or(self, either: EdgeQuery, or_: EdgeQuery) -> None: ...
will do during the actual implementation when the feasability of this is clearer

2024-09-04 10:52 UTC, LauraBoenchenLB approved these changes
Very cool new query engine! Can't wait to use it to build complex queries with 😎

2024-09-04 10:57 UTC, merged