feat: Adding contingency table print and treatment groups variables renaming
limebit/medmodels pull request #211
Opened 2024-09-17 14:29 UTC by MarIniOnz

Added a function that better visualizes how the different control and treated groups are separated.

Also renamed the following variables everywhere for clarity purposes:
- treatment_true: "treatment_outcome_true"
- treatment_false: "treatment_outcome_false"
- control_true: "treatment_control_true"
- control_false: "treatment_control_false"

``` python
TretmentEffect.estimate.print_contingency_table(medrecord)
```
```
-----------------------------------
                   Outcome   
Group           True     False   
-----------------------------------
Treated         2        1       
Control         3        3       
-----------------------------------
```

2024-09-17 14:45 UTC, JabobKrauskopf requested changes
Why not return an actual object (custom object, not typed dictionary) at `subjects_contingency_table` and implement the `__str__` method on that object to pretty print it? That way the object is usable in basically the same way as the TypedDict and can automatically be pretty printed in the console or jupyter notebooks

Using `print` in a package is generally not a good idea because of the way stdio works differently on some machines (or is inaccessible). That's why you also generally don't see any `print_...` methods in other packages

2024-09-17 14:50 UTC, philippgrosser commented on medmodels/treatment_effect/continuous_estimators.py
>              treated group.
Isnt that the set that represents nodes that are true for outcome and treatment? Therefore the sentence _"A set of node indices representing the treated group."_ would be incorrect?

2024-09-18 10:12 UTC, JabobKrauskopf requested changes
much better.

IMO we should keep the `subject_counts` method. The object that is returned from there should implement the `__str__` method that is implemented for `TreatmentEffectGroups` currently.
Then the `subjects_contingency_table` either returns the dictionary as before or keeps returning a custom object with another `__str__` function that does not print the number of subjects but the actual indices list.

2024-09-18 10:12 UTC, JabobKrauskopf commented on medmodels/treatment_effect/estimate.py
> +class TreatmentEffectGroups:
should probably be called contingency table

2024-09-18 12:02 UTC, JabobKrauskopf approved these changes
PR APPROVED! But don’t get cocky, recruit! This is just one battle in the war of clean code. I expect nothing less than perfection next time. Now, get back out there and refactor like your IDE is on fire! OORAH /s

2024-09-18 12:05 UTC, MarIniOnz commented
> PR APPROVED! But don’t get cocky, recruit! This is just one battle in the war of clean code. I expect nothing less than perfection next time. Now, get back out there and refactor like your IDE is on fire! /s

AYE CAPTAIN!

2024-09-18 12:46 UTC, philippgrosser approved these changes
Very nice! Looking forward to use this!

2024-09-18 12:47 UTC, merged