feat: Adding Critic module and associated functions
limebit/medmodels pull request #223
Opened 2024-09-26 11:51 UTC by MarIniOnz

Adding the Critic Module which discriminates between real and synthetic data.

2024-10-09 11:23 UTC, LauraBoenchenLB requested changes
Few comments, mostly just about doc strings. Critic is looking great!!

2024-10-09 11:23 UTC, LauraBoenchenLB commented on medmodels/data_synthesis/mtgan/model/critic/critic.py
> +            device (torch.device): Device to run the model on
```suggestion
        Args:
            real_gru (RealGRU): Real GRU model.
            total_number_of_concepts (int): Size of input features (number of codes).
            hyperparameters (TrainingHyperparameters): Hyperparameters for training.
            device (torch.device): Device to run the model on.
```

2024-10-09 11:23 UTC, LauraBoenchenLB commented on medmodels/data_synthesis/mtgan/model/critic/critic.py
> +            device (torch.device): Device to run the model on
All the docstrings

2024-10-09 11:23 UTC, LauraBoenchenLB commented on medmodels/data_synthesis/mtgan/model/critic/loss.py
> +        # Ensure no gradients are calculated for this section to save memory and compute
```suggestion
        # Ensure no gradients are calculated for this section to save memory and computational power.
```

?

2024-10-09 19:07 UTC, JabobKrauskopf requested changes
some teeny tiny changes requested

2024-10-09 19:07 UTC, JabobKrauskopf commented on medmodels/data_synthesis/mtgan/model/critic/critic.py
> +        self.scheduler.step()
a bit more spacing

2024-10-09 19:07 UTC, JabobKrauskopf commented on medmodels/data_synthesis/mtgan/model/critic/critic.py
> +            return loss
a bit more spacing

2024-10-09 19:07 UTC, JabobKrauskopf commented on medmodels/data_synthesis/mtgan/model/critic/loss.py
> +        self.lambda_ = lambda_
could there be a better name to use here instead of `lambda` so you don't have to add the `_`? If nothing comes to mind then that's fine :)

2024-10-09 19:07 UTC, JabobKrauskopf commented on medmodels/data_synthesis/mtgan/model/critic/loss.py
> +        return critic_loss, wasserstein_distance
a bit more spacing

2024-10-10 09:33 UTC, JabobKrauskopf requested changes
one smol thing

2024-10-10 09:59 UTC, JabobKrauskopf approved these changes
![image](https://github.com/user-attachments/assets/59945485-2efb-4971-963e-c17aa6e00834)

2024-10-10 10:17 UTC, LauraBoenchenLB approved these changes
Let's gooooo MTGAN 🦭

2024-10-10 11:01 UTC, merged