fix: linting and docstrings issues in treatment effect module
limebit/medmodels pull request #249
Opened 2024-10-21 15:58 UTC by MarIniOnz

Fixing linting and dosctrings in all treatment effect files. Some rework was done in `continuous.estimators.py` to add hedges_g since the add_correction boolean argument was against linting conventions.

2024-11-04 15:01 UTC, MarIniOnz commented on medmodels/treatment_effect/builder.py
>          if essential_covariates is None:
I will write in the medmodels thread for an issue about this! Let's leave it like this for now. But you are very righT!

2024-11-04 15:02 UTC, MarIniOnz commented on medmodels/treatment_effect/continuous_estimators.py
> +    cohen_d = (treated_outcomes.mean() - control_outcomes.mean()) / pooled_std_dev
completely right

2024-11-05 11:20 UTC, LauraBoenchenLB commented on medmodels/treatment_effect/builder.py
>          if essential_covariates is None:
exactly, that doesn't need to be in this PR :)

2024-11-05 11:22 UTC, LauraBoenchenLB commented
Question: The linting error is expected because this PR only fixes the linting issues in the treatment effect module?

2024-11-05 11:52 UTC, MarIniOnz commented
> Question: The linting error is expected because this PR only fixes the linting issues in the treatment effect module?

Exactly, linting error on all but Treatment Effect module should be expected!

2024-11-05 13:05 UTC, LauraBoenchenLB approved these changes
Looks great to me! 🦭

2024-11-20 00:10 UTC, JabobKrauskopf requested changes
very minor stuff

2024-11-20 00:10 UTC, JabobKrauskopf commented on medmodels/treatment_effect/builder.py
> +desired configurations for the treatment effect estimation using a builder pattern.
imo this information should be under the actual `TreatmentEffectBuilder` and not the module description

2024-11-20 00:10 UTC, JabobKrauskopf commented on medmodels/treatment_effect/matching/algorithms/classic_distance_models.py
> +This module contains the implementation of the nearest neighbor matching algorithm.
not necessary imo

2024-11-20 00:10 UTC, JabobKrauskopf commented on medmodels/treatment_effect/matching/matching.py
> +"""Matching abstract class.
this is not the matching abstract class. it is the module that includes the abstract class

2024-11-20 00:10 UTC, JabobKrauskopf commented on medmodels/treatment_effect/treatment_effect.py
> +        """Initializes a Treatment Effect analysis setup.
sounds weird (also sounded weird before)

2024-11-20 00:10 UTC, JabobKrauskopf commented on medmodels/treatment_effect/treatment_effect.py
> +        """Initializes a Treatment Effect analysis setup.
also sounds weird and is not really what it does

2024-11-28 14:26 UTC, LauraBoenchenLB approved these changes
My approval stands 🫡

2025-01-02 09:30 UTC, JabobKrauskopf approved these changes
![Screen Shot 2025-01-02 at 10 30 12](https://github.com/user-attachments/assets/0869c693-21f1-4e59-9294-74ced54e9b39)

2025-01-02 10:00 UTC, merged