docs: apply links to functions and new sphinx extension to guide
limebit/medmodels pull request #276
Opened 2024-12-09 13:42 UTC by MarIniOnz

The different functions and methods were linked in the Query Engine guide.

I implemented that logic, apart from the new sphinx extension that executes cells in all of the user guide so it is coherent.

2024-12-17 14:32 UTC, LauraBoenchenLB requested changes
Looks great! Very useful to have the functions linked directly 🤩

2024-12-17 14:32 UTC, LauraBoenchenLB commented on docs/user_guide/02_medrecord.md
> +- [`node[]`](medmodels.medrecord.medrecord.MedRecord.node){target="_blank"} : Provides access to node attributes within the MedRecord instance via an indexer.
maybemention that it returns a dict wth the attributes

2024-12-17 14:32 UTC, LauraBoenchenLB commented on docs/user_guide/02_medrecord.md
> +The MedRecord can be queried in very advanced ways in order to find very specific nodes based on time, relations, neighbors or other. These advanced querying methods are covered in one of the next se
Possibly link the query section

2024-12-17 14:32 UTC, LauraBoenchenLB commented on docs/user_guide/02b_query_engine.md
> +- [`in_group()`](medmodels.medrecord.querying.EdgeOperand.in_group){target="_blank"} : Query nodes that belong to that group.: Query edges that belong to that group.
```suggestion
- [`in_group()`](medmodels.medrecord.querying.EdgeOperand.in_group){target="_blank"} : Query nodes that belong to that group.
```

2025-01-10 17:13 UTC, LauraBoenchenLB requested changes
Last spell check! :)

2025-01-10 17:13 UTC, LauraBoenchenLB commented on docs/user_guide/getstarted.md
> +* [`group()`](medmodels.medrecord.medrecord.MedRecord.group){target="_blank"} : Returns the node and edge indices associated with the specified group/s in the MedRecord.
```suggestion
* [`group()`](medmodels.medrecord.medrecord.MedRecord.group){target="_blank"} : Returns the node and edge indices associated with the specified group(s) in the MedRecord.
```

2025-01-10 17:13 UTC, LauraBoenchenLB commented on docs/user_guide/getstarted.md
> +All outgoing or incoming edges of a node or a list of nodes can be retrieved with the functions [`outgoing_edges()`](medmodels.medrecord.medrecord.MedRecord.outgoing_edges){target="_blank"} or [`inco
```suggestion
All outgoing or incoming edges of a node or a list of nodes can be retrieved with the functions [`outgoing_edges()`](medmodels.medrecord.medrecord.MedRecord.outgoing_edges){target="_blank"} or [`incoming_edges()`](medmodels.medrecord.medrecord.MedRecord.incoming_edges){target="_blank"}, respectively. If the edges of a list of nodes is requested, the return will be a dictionary with the nodes as keys and their edges as values in lists. Otherwise for a single node, the return will be a simple list.
```

2025-01-10 17:13 UTC, LauraBoenchenLB commented on docs/user_guide/getstarted.md
> +* [`attribute()`](medmodels.medrecord.querying.EdgeOperand.attribute){target="_blank"} : Returns a [`MultipleValuesOperand()`](medmodels.medrecord.querying.MultipleValuesOperand){target="_blank"} to
```suggestion
* [`attribute()`](medmodels.medrecord.querying.EdgeOperand.attribute){target="_blank"} : Returns a [`MultipleValuesOperand()`](medmodels.medrecord.querying.MultipleValuesOperand){target="_blank"} to query on the values of the edges for that attribute.
```

2025-01-13 09:32 UTC, MarIniOnz commented on docs/user_guide/getstarted.md
> +* [`add_edges_polars()`](medmodels.medrecord.medrecord.MedRecord.add_edges_polars){target="_blank"} : Adds nodes to the MedRecord from different data formats and optionally assigns them to a group.
It was not used in the snippet!

2025-01-13 10:00 UTC, LauraBoenchenLB commented on docs/user_guide/getstarted.md
> +* [`add_edges_polars()`](medmodels.medrecord.medrecord.MedRecord.add_edges_polars){target="_blank"} : Adds nodes to the MedRecord from different data formats and optionally assigns them to a group.
```suggestion
* [`add_edges_polars()`](medmodels.medrecord.medrecord.MedRecord.add_edges_polars){target="_blank"} : Adds edges to the MedRecord from Polars data frame and optionally assigns them to a group.
```

2025-01-13 10:02 UTC, MarIniOnz commented on docs/user_guide/getstarted.md
> +* [`add_edges_polars()`](medmodels.medrecord.medrecord.MedRecord.add_edges_polars){target="_blank"} : Adds nodes to the MedRecord from different data formats and optionally assigns them to a group.
True! solved!

2025-01-13 10:03 UTC, LauraBoenchenLB submitted a review, later dismissed
✨ Perfection ✨

2025-01-14 13:18 UTC, closed without merging