refactor: Apply all typing changes in medmodels/matching according to pyright
limebit/medmodels pull request #95
Opened 2024-05-27 12:02 UTC by MarIniOnz

2024-05-27 13:56 UTC, LauraBoenchenLB reviewed
Just one question where I'm not sure if the use of the argument is right. Otherwise great PR, the typing looks great and tests also match!

2024-05-27 13:56 UTC, LauraBoenchenLB commented on medmodels/matching/metrics.py
> +def absolute_metric(*vectors: NDArray[np.float64]) -> float:
Can we still use the * here if the input is a NDArray and not a Tuple?

2024-05-27 13:56 UTC, LauraBoenchenLB commented on medmodels/matching/metrics.py
> +def exact_metric(*vectors: NDArray[np.float64]) -> float:
Same question

2024-05-27 14:13 UTC, MarIniOnz commented on medmodels/matching/metrics.py
> +def exact_metric(*vectors: NDArray[np.float64]) -> float:
Same.

2024-05-27 15:58 UTC, JabobKrauskopf approved these changes
Nice job! :)

Minor adjustments and please add `matching` to the pyright config in `pyproject.toml` (in this PR)

2024-05-27 16:23 UTC, JabobKrauskopf requested changes
sry i meant to request changes

2024-05-28 10:23 UTC, JabobKrauskopf commented on medmodels/matching/covariates/covariates_preprocessing.py
> +    covariate: pd.Series[Union[int, float]], n_digits: int = 2
Should `n_digits` be `n_digits: Optional[int] = 2`?

2024-05-28 10:54 UTC, JabobKrauskopf approved these changes
Good job!

2024-05-28 11:03 UTC, LauraBoenchenLB approved these changes

2024-05-28 11:04 UTC, merged